"""
Django settings for plaque_immatriculation project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# ------------------------------------------------------------------------
# 📌 Construction des chemins à l'intérieur du projet
# ------------------------------------------------------------------------

# Base du projet (répertoire racine)
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------
# 📌 Sécurité et configuration de base
# ------------------------------------------------------------------------

# ⚠️ Clé secrète pour le chiffrement (changer en production !)
SECRET_KEY = 'django-insecure-3(*u!^)*-b$co!nf#d*22f@o1^8vpiq_at-gnj@x+!63(y3^(n'

# ⚠️ Désactiver DEBUG en production !
DEBUG = True

# Définition des hôtes autorisés (mettre le domaine en production)
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# ------------------------------------------------------------------------
# 📌 Applications Django
# ------------------------------------------------------------------------

INSTALLED_APPS = [
    'rootvibe',  # 🟢 Application principale de ton projet
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# ------------------------------------------------------------------------
# 📌 Middlewares (Gestion de la sécurité et des requêtes)
# ------------------------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------------------------------------------------
# 📌 URL racine de l'application
# ------------------------------------------------------------------------

ROOT_URLCONF = 'plaque_immatriculation.urls'

# ------------------------------------------------------------------------
# 📌 Configuration des templates
# ------------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 📂 Répertoire des templates personnalisés
        'APP_DIRS': True,  # 📌 Recherche aussi les templates dans les applications installées
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'rootvibe.context_processors.user_groups',  # ⚡ Ajout du context processor personnalisé
            ],
        },
    },
]

# ------------------------------------------------------------------------
# 📌 Configuration WSGI (Serveur Web)
# ------------------------------------------------------------------------

WSGI_APPLICATION = 'plaque_immatriculation.wsgi.application'

# ------------------------------------------------------------------------
# 📌 Base de données
# ------------------------------------------------------------------------

# ⚠️ SQLite utilisé pour le développement (remplacer par PostgreSQL en production)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ------------------------------------------------------------------------
# 📌 Validation des mots de passe (sécurité)
# ------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------------------------------------
# 📌 Paramètres régionaux et fuseau horaire
# ------------------------------------------------------------------------

# 🌍 Langue et fuseau horaire
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------------------
# 📌 Fichiers statiques et médias (CSS, JS, images, uploads)
# ------------------------------------------------------------------------

# 📁 Gestion des fichiers statiques
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,  'rootvibe','static')]
 # 📌 Dossier où Django cherche les fichiers statiques
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # 📌 Dossier utilisé pour collecter tous les fichiers statiques en production

# 📁 Gestion des fichiers médias (uploads des utilisateurs)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ------------------------------------------------------------------------
# 📌 Gestion des utilisateurs et authentification
# ------------------------------------------------------------------------

# ⚡ Utilisation d'un modèle utilisateur personnalisé
AUTH_USER_MODEL = 'rootvibe.User'

# 📌 Configuration des URLs d'authentification
LOGIN_URL = 'login'  # Page de connexion
LOGIN_REDIRECT_URL = "/home/"  # Page après connexion
LOGOUT_REDIRECT_URL = 'login'  # Page après déconnexion

# ------------------------------------------------------------------------
# 📌 Sécurité et protection CSRF
# ------------------------------------------------------------------------

# 🔒 Sécurisation des sessions et des cookies
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 86400  # 🕒 1 jour (en secondes)
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_SECURE = False  # ⚠️ Mettre sur True en production avec HTTPS
CSRF_COOKIE_SECURE = False  # ⚠️ Mettre sur True en production avec HTTPS
CSRF_USE_SESSIONS = True  # 🔒 Stocke le token CSRF dans la session utilisateur

# 📌 Pour éviter l'erreur CSRF (ex: lors de connexions locales)
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000", "http://localhost:8000"]

# ------------------------------------------------------------------------
# 📌 Configuration des modèles
# ------------------------------------------------------------------------

# 🔹 Clé par défaut pour les nouveaux modèles de la base de données
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
