# Generated by Django 5.1.2 on 2025-02-08 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootvibe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(default='TAJIRI', max_length=50)),
                ('payment_type', models.CharField(default='1', max_length=10)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide. Le format doit être +243XXXXXXXX ou 0XXXXXXXX.', regex='^(?:\\+243|0)[1-9]\\d{7,8}$')])),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CDF', max_length=10)),
                ('callbackUrl', models.URLField(default='http://localhost')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('success', 'Réussi'), ('failed', 'Échoué')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
