# Generated by Django 5.1.2 on 2025-02-05 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootvibe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisConduire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_permis', models.CharField(max_length=15, unique=True)),
                ('date_delivrance', models.DateField(auto_now_add=True)),
                ('points', models.IntegerField(default=12)),
                ('statut', models.CharField(choices=[('attente', 'En attente de validation'), ('valide', 'Valide'), ('suspendu', 'Suspendu')], default='attente', max_length=10)),
                ('photo_identite', models.ImageField(blank=True, null=True, upload_to='permis_photos/')),
                ('proprietaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rootvibe.proprietaire')),
            ],
        ),
    ]
