# Generated by Django 5.1.2 on 2025-02-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootvibe', '0002_permisconduire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire',
            name='sex',
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='plaque_immatriculation',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DemandePlaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='attente', max_length=10)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootvibe.proprietaire')),
                ('vehicule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rootvibe.vehicule')),
            ],
        ),
    ]
